version: '3'
services:
  snippetbox:
    build:
      dockerfile: ./cmd/web/main.dockerfile
    ports:
      - "4000:4000"
    container_name: snippetbox
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "snippetbox:password@tcp(mysql:3306)/snippetbox?charset=utf8mb4&parseTime=True"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=snippetbox
      - MYSQL_USER=snippetbox
      - MYSQL_PASSWORD=password
    volumes:
      - ./db-data/mysql/:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 3

